#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------
make

restore0Dir

runApplication blockMesh

runApplication setFields

decomposePar -force
#runApplication $(getApplication)


mpirun -np 2 interFoam -parallel -mpi-split-by-appnum : -np 1 ./ping

#------------------------------------------------------------------------------
